### PR TITLE
Fix: Allow user to provide input props

### LINKED ISSUE #82: Don't change event handling
```jsx
function myHandler ( event ) {}
<input type='checkbox' onChange={ myHandler } />
```

Then, if I were to switch to use this library,
```jsx
/* <input type='checkbox' onChange={ myHandler } /> */
<Checkbox onChange={ myHandler } />
```
it breaks.

It fires twice: once with the value, once with the Event.

I would much prefer to have my event handling all work the same: handle the event, let the handler work out what they find useful.

Please change to not intercept the native events.
Same request for Textfield and others.

Thanks for the library, by the way. It's so much easier than using all the mdl classnames

### PR DESCRIPTION
**Pull request by joshq00**
Fixes #82

* Update change events use `event` instead of `value`.
* Props solely used for `input` components, where able, are directly passed

There are still some components where value, id, name are handled manually.

### CODE REVIEW

**Comment by tleunen** [comment]
Thanks @joshq00! I really appreciate the help to make `react-mdl` better :)

I understand we could do a cleanup in the `propTypes` of every component, but is some cases and especially when they are flagged "required", I think it's good to have them. It forces the user to use/set them and to know what's available on the component.

**Comment by joshq00** [comment]
I don't see any problem with keeping them in the `propTypes`, or documenting that all `input` attributes are valid props.

However, I don't think they should be required if they are not required on the native input element.

For example, if I want a text box without a label (maybe I'm just using `placeholder`, or putting my label elsewhere) - I have to do
```jsx
<Textfield label="" />
```
Without doing label="", I don't just get an invariant warning... I actually get an error thrown

**Comment by tleunen** [comment]
I think it really depends. Because you know how the component is built, you know you can use a lot of props that are not described. But ideally, props should describe what you can use (or at least those who are supported and tested). A slider without the min/max value for example doesn't make a lot of sense, but because it's an input behind the scene, you know you can provide them.

**Comment by joshq00** [comment]
I made a [fiddle](http://jsfiddle.net/4n5nqxya/1/) testing behavior with/without labels

**Comment by tleunen** [comment]
Yes the input still works. But it doesn't have the MDL styles. Label is required with a MDL Textfield, we cannot change that.

**Comment by joshq00** [comment]
Fair enough.

Anyhow, I didn't remove `isRequired` from the label property. Would you like me to add other properties?

**Comment by tleunen** [comment]
For now, because there's no documentation, I prefer keeping the propTypes because they are kind of a documentation as well.

Could you rebase instead of merge? To avoid having these merge commits ? :)
Thanks!

**Comment by joshq00** [comment]
Rebased

**Comment by tleunen** [comment]
Could you please only change the way the event is sent inside `onChange`?
As I said, I prefer keeping the other props to serve as a documentation.

**Comment by joshq00** [comment]
I'll get those back in today or tomorrow at latest

**Comment by joshq00** [comment]
@tleunen should be all ready now

File: src/RadioGroup.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ class RadioGroup extends React.Component {
         }),
         container: PropTypes.string,
         name: PropTypes.string.isRequired,
-        onChange: PropTypes.func.isRequired,
+        onChange: PropTypes.func,
```
Comment (tleunen) [inline src/RadioGroup.js]: any reason why it's not required anymore?
Usually, React wants us to provide an `onChange` callback if we set a `value`.
This is valable for every input.

File: src/Slider.js [hunk 2]
```diff
@@ -5,18 +5,14 @@ import mdlUpgrade from './utils/mdlUpgrade';
 class Slider extends React.Component {
     static propTypes = {
         className: PropTypes.string,
-        max: PropTypes.number.isRequired,
-        min: PropTypes.number.isRequired,
-        onChange: PropTypes.func.isRequired,
+        max: PropTypes.number,
```
Comment (tleunen) [inline src/Slider.js]: Why it's not required anymore?
Creating a Slider without the min/max doesn't make any sense

File: src/Slider.js [hunk 3]
```diff
@@ -5,18 +5,14 @@ import mdlUpgrade from './utils/mdlUpgrade';
...
+        min: PropTypes.number,
+        onChange: PropTypes.func,
```
Comment (tleunen) [inline src/Slider.js]: Same here, I can't think of a scenario where we won't set the callback

File: src/Slider.js [hunk 4]
```diff
@@ -24,11 +20,6 @@ class Slider extends React.Component {
             <input
                 className={classes}
                 type="range"
-                min={min}
-                max={max}
-                value={value}
-                tabIndex="0"
```
Comment (tleunen) [inline src/Slider.js]: It's needed. Upstream set the value so there's no reason we don't do the same.

File: src/Tabs/Tabs.js [hunk 5]
```diff
@@ -13,7 +13,7 @@ class Tabs extends React.Component {
             }
         }),
         className: PropTypes.string,
-        onChange: PropTypes.func.isRequired,
+        onChange: PropTypes.func,
```
Comment (tleunen) [inline src/Tabs/Tabs.js]: Same, isRequired?

File: src/RadioGroup.js (hunk 1 above)
Comment (joshq00) [inline src/RadioGroup.js]: Exactly my reasoning. React already handles the checking and it's not required on the true input element. Warnings will show as they should, and the user will interact with the element like they would a normal input element.

As a user, I might not care to listen to the `onChange` event. I may be prototyping.

Especially in the case of the other input types, I often use `defaultValue` instead of `value`+`onChange`

Making the fewest assumptions about what the user "meant to do" keeps the library from limiting what they can do

File: src/Slider.js (hunk 2 above)
Comment (joshq00) [inline src/Slider.js]: But it's allowed. None of those are required properties on input elements. For example, `<input type="range" max="100" />` is valid.

Also, consider `<Slider disabled />`

File: src/Slider.js (hunk 3 above)
Comment (joshq00) [inline src/Slider.js]: `<Slider disabled />`

File: src/RadioGroup.js (hunk 1 above)
Comment (tleunen) [inline src/RadioGroup.js]: Yeah the only reason why I see onChange not beeing required is just for prototyping because otherwise you have no way to get the value from the input.

File: src/Slider.js (hunk 4 above)
Comment (joshq00) [inline src/Slider.js]: `<Slider defaultValue={ 25 } max={ 100 } />`

File: src/RadioGroup.js (hunk 1 above)
Comment (joshq00) [inline src/RadioGroup.js]: Or, one could have a dom listener registered

Comment (tleunen) [inline src/RadioGroup.js]: seriously?! Either you use react, or you don't...

I understand it's nice to be generic, but I think there's a limit to that lol

Comment (joshq00) [inline src/RadioGroup.js]: Not exactly. Take Facebook for example. The majority of the site was done directly mutating dom and they implemented react just for the chat section. There's a reason Facebook doesn't make assumptions about what we _meant_ to do. I can have a full blown site that I just drop in a React component for one piece. That shouldn't break the rest of my app.

File: src/Slider.js (hunk 2 above)
Comment (tleunen) [inline src/Slider.js]: Indeed. It seems they have a default min-max of 0-100 with 20 as the default value.
Agreed with disabled.

File: src/RadioGroup.js (hunk 1 above)
Comment (joshq00) [inline src/RadioGroup.js]: Another example is if the user is looking at `onClick` instead of `onChange`. Or `onTouchStart`/`onTouchEnd`

Assumptions make an opinionated framework and, if I wanted that, I'd use ember or angular

File: src/Slider.js (hunk 4 above)
Comment (tleunen) [inline src/Slider.js]: I was taking about the `tabIndex` ;)

**Comment by tleunen** [comment]
In general, yes we can set the onChange callback as optional. It helps prototyping screen. But usually people will set it anyway because we usually create controlled form. (using value + onChange).

File: src/Slider.js (hunk 4 above)
Comment (joshq00) [inline src/Slider.js]: Doesn't tabindex have a default of 0 anyhow? I'd have to check into it, but I'm pretty sure that's the case

**Comment by joshq00** [comment]
100% agree - you'll probably will want to register a handler... but you might not. there are a million edge cases where you could be accomplishing the same thing.

A use case for not having `value` is if I'm using a store to keep track of the freeform text instead of state.
Another use case is that, sometimes, I need to use `onKeyUp` instead of `onChange`. By requiring it, I need to do `onChange={ () => {} }` just to avoid all the warnings

File: src/Slider.js (hunk 4 above)
Comment (tleunen) [inline src/Slider.js]: Yep, I think it's the default value. Might be better to ask upstream why they specify the tabIndex value then before changing it here. Because they have it in all their demos.

Comment (joshq00) [inline src/Slider.js]: I just tried it : without `tabIndex=0`, tabbing through still works properly.

tabindex=0 should be the default for any focusable element

Comment (tleunen) [inline src/Slider.js]: Could you open an issue upstream to ask them and follow up on this?

Comment (joshq00) [inline src/Slider.js]: I just checked their [slider samples](http://www.getmdl.io/components/index.html#sliders-section) and, if you scroll down to "Example," they do show usage without setting `tabindex`

**Comment by faergeek** [comment]
@tleunen Take a look at this about `onChange` https://github.com/tleunen/react-mdl/issues/55

**Comment by tleunen** [comment]
Yep I forgot about this valueLink. But I agree with the changes. I'll merge once I get a confirmation for the tabindex thing. I asked them on their gitter channel.
